[WIP] - GraphQL
jaypathar/node pull request #11
Opened 2023-08-29 13:02 UTC by jaypathar

2023-08-29 14:11 UTC, RenishIs requested changes

2023-08-29 14:11 UTC, RenishIs commented on _GraphQL/index.js
> +    `,
Let's Extract Types into diffrent file

2023-09-01 08:32 UTC, RenishIs approved these changes

2023-09-01 08:39 UTC, albiorixvimal approved these changes
Please address minor comments and merge it

2023-09-01 08:39 UTC, albiorixvimal commented on _GraphQL/index.js
> +// startServer();
Create a separate file if this code required otherwise remove it

2023-09-01 08:39 UTC, albiorixvimal commented on _GraphQL/index.js
> +        getAllUsers: userResolver,
rename it to `getUsers` to consistency in naming conventions

2023-09-01 08:47 UTC, merged